package es.seap.minhap.ws;

import es.seap.minhap.utilidades.Utilidades;
import java.net.URL;
import java.util.Properties;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5 2013-05-20T11:56:47.733+02:00
 * Generated source version: 2.7.5
 *
 */
@WebServiceClient(name = "DigitaWS",
        targetNamespace = "http://ws.minhap.seap.es/")
public class DigitaWS_Service extends Service {

    public static URL WSDL_LOCATION = null;
    public final static QName SERVICE = new QName("http://ws.minhap.seap.es/", "DigitaWS");
    public final static QName DigitaWSPort = new QName("http://ws.minhap.seap.es/", "DigitaWSPort");

  //  private static String rutaws = "http://progdcaptura3.mpt.es:9001/digita-ws/DigitaWS?wsdl";
    static Utilidades util = new Utilidades();
    static Properties prop = util.leerConfiguracion("es/jscan/ws/propiedades/ws-servidor.properties");
    private static String rutaws = prop.getProperty("wsurl");
    static {
        try {
            URL url = new URL(rutaws);

            WSDL_LOCATION = url;
        } catch (Exception e) {
            WSDL_LOCATION = null;
        }
    }

    public DigitaWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DigitaWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DigitaWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return returns DigitaWS
     */
    @WebEndpoint(name = "DigitaWSPort")
    public DigitaWS getDigitaWSPort() {
        return super.getPort(DigitaWSPort, DigitaWS.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in
     * the <code>features</code> parameter will have their default values.
     * @return returns DigitaWS
     */
    @WebEndpoint(name = "DigitaWSPort")
    public DigitaWS getDigitaWSPort(WebServiceFeature... features) {
        return super.getPort(DigitaWSPort, DigitaWS.class, features);
    }
}
