package es.jscan.Pantallas;

import es.jscan.utilidades.TablaSinEditarCol;
import es.jscan.utilidades.Utilidades;
import java.util.Properties;
import java.util.StringTokenizer;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTable;

public class PantallaTablaDatos extends javax.swing.JDialog {

    public String rutafichero = "";

    public PantallaTablaDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rutafichero = parent.getName();
        this.setTitle(parent.getTitle());
        cargarTabla();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTabla = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        botonAceptar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Principal"); // NOI18N
        setResizable(false);

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Archivo", "Nº Páginas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTabla.setViewportView(tablaDatos);

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 145, Short.MAX_VALUE)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(botonAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Utilidades.escribeLog("Error en el main de PantallaTablaDatos "  + " - " + ex.getMessage());
        } catch (InstantiationException ex) {
            Utilidades.escribeLog("Error en el main de PantallaTablaDatos "  + " - " + ex.getMessage());
        } catch (IllegalAccessException ex) {
            Utilidades.escribeLog("Error en el main de PantallaTablaDatos "  + " - " + ex.getMessage());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Utilidades.escribeLog("Error en el main de PantallaTablaDatos "  + " - " + ex.getMessage());
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PantallaTablaDatos dialog = new PantallaTablaDatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonAceptar;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables

        private void asignarIconos() {
        java.net.URL imgURL = PantallaLotesGuardados.class.getClassLoader().getResource("es/jscan/Pantallas/imagenes/si.png");
        Icon imgicon = new ImageIcon(imgURL);
        this.botonAceptar.setIcon(imgicon);

    }
    
    private void cargarTabla() {
        if (rutafichero.isEmpty()) {
            return;
        }
        Utilidades util = new Utilidades();
        Properties props = util.leerPropeties(rutafichero);
        String documentos = props.getProperty("documentos");
        String docs[] = documentos.split(";");
        int numdocs = docs.length;

        if (numdocs <= 0) {
            TablaSinEditarCol modeloLotes = new TablaSinEditarCol();
            tablaDatos.setModel(modeloLotes);
            tablaDatos.doLayout();
            return;
        }

        Object[] cabecera = {"Documento", "Nº Páginas"};
        Object[][] datos = new Object[numdocs][2];

        for (int i = 0; i < numdocs; i++) {
            //  String valores[] = docs[i].split("|");
            StringTokenizer valores = new StringTokenizer(docs[i], "|");
            int n = 0;
            while (valores.hasMoreTokens()) {
                datos[i][n] = valores.nextToken();
                n++;
            }
        }

        final TablaSinEditarCol modeloLotes = new TablaSinEditarCol(datos, cabecera);

        try {
            tablaDatos.setModel(modeloLotes);
        } catch (Exception e) {
            Utilidades.escribeLog(e.getMessage());
        }

        tablaDatos.setShowHorizontalLines(true);
        tablaDatos.setRowSelectionAllowed(true);
        tablaDatos.setAutoCreateRowSorter(true);
        tablaDatos.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);

        tablaDatos.getColumnModel().getColumn(0).setPreferredWidth(150);
        tablaDatos.doLayout();
    }
}
