package es.jscan.Pantallas;

import es.jscan.utilidades.Utilidades;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author julian
 */
public class PantallaSeleccion extends javax.swing.JDialog {

    /**
     * Creates new form PantallaSeleccion
     */
    public static String valor = "";
    public static String[] lista = null;
    public static PantallaPrincipal ventanapadre = null;

    public static String[] getLista() {
        return lista;
    }

    public static void setLista(String[] lista) {
        if (lista != null) {
            PantallaSeleccion.lista = lista;
        }
    }

    public static String getValor() {
        return valor;
    }

    public static void setValor(String valor) {
        PantallaSeleccion.valor = valor;
    }

    public PantallaSeleccion(PantallaPrincipal parent, boolean modal) {
        super(parent, modal);
        ventanapadre = parent;
        initComponents();
        setLista(parent.listaseleccion);
        setTitle(parent.titulolista);
        asignariconos();
        cargarLista();
        setLocationRelativeTo(ventanapadre);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSeleccion = new javax.swing.JScrollPane();
        ListaSeleccion = new javax.swing.JList();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ListaSeleccion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaSeleccion.setName("ListaSeleccion"); // NOI18N
        PanelSeleccion.setViewportView(ListaSeleccion);
        ListaSeleccion.getAccessibleContext().setAccessibleName("ListaSeleccion");

        botonAceptar.setMnemonic('A');
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(botonAceptar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(PanelSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAceptar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if (ListaSeleccion.getModel().getSize() > 0) {
            valor = ListaSeleccion.getModel().getElementAt(ListaSeleccion.getSelectedIndex()).toString();
        }
        dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Utilidades.escribeLog("Error en el main de PantallaSeleccion " + " - " + ex.getMessage());
        } catch (InstantiationException ex) {
            Utilidades.escribeLog("Error en el main de PantallaSeleccion " + " - " + ex.getMessage());
        } catch (IllegalAccessException ex) {
            Utilidades.escribeLog("Error en el main de PantallaSeleccion " + " - " + ex.getMessage());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Utilidades.escribeLog("Error en el main de PantallaSeleccion " + " - " + ex.getMessage());
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PantallaSeleccion dialog = new PantallaSeleccion(ventanapadre, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(ventanapadre);
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListaSeleccion;
    private javax.swing.JScrollPane PanelSeleccion;
    private javax.swing.JButton botonAceptar;
    // End of variables declaration//GEN-END:variables

    public void cargarLista() {
        if (lista == null) {
            return;
        }
        DefaultListModel ModeloLista = new DefaultListModel();

        for (int i = 0; i < lista.length; i++) {
            ModeloLista.add(i, lista[i]);
            if (PantallaPrincipal.DEBUG) {
                Utilidades.escribeLog("Elemento " + i + ": " + lista[i]);
            }
        }
        ListaSeleccion.setModel(ModeloLista);
        ListaSeleccion.setSelectedIndex(0);
    }

    public void asignariconos() {
        java.net.URL imgURL = PantallaSeleccion.class.getResource("imagenes/si.png");
        Icon imgicon = new ImageIcon(imgURL);
        botonAceptar.setIcon(imgicon);

    }
}
